export const danhSachBenhNhanCapPhat = [
  { id: 1, doiTuong: 'BHYT', hoTen: 'CẤP THỊ ÁNH NHUNG', maBN: '2604053176', phai: 'Nữ' },
  { id: 2, doiTuong: 'BHYT', hoTen: 'DƯƠNG THỊ KIM KHANH', maBN: '2507043514', phai: 'Nữ' },
  { id: 3, doiTuong: 'BHYT', hoTen: 'LÊ THỊ TỐI', maBN: '2502038475', phai: 'Nữ' },
  { id: 4, doiTuong: 'BHYT', hoTen: 'NGUYỄN SANG', maBN: '2308021910', phai: 'Nam' },
  { id: 5, doiTuong: 'BHYT', hoTen: 'NGUYỄN THANH LONG', maBN: '2604052328', phai: 'Nam' },
  { id: 6, doiTuong: 'BHYT', hoTen: 'NGUYỄN THỊ HÀ', maBN: '2502038614', phai: 'Nữ' },
  { id: 7, doiTuong: 'BHYT', hoTen: 'NGUYỄN VĂN HÙNG', maBN: '2506043101', phai: 'Nam' },
  { id: 8, doiTuong: 'BHYT', hoTen: 'PHẠM THỊ BẦN', maBN: '2601049583', phai: 'Nữ' },
  { id: 9, doiTuong: 'BHYT', hoTen: 'VÕ VĂN GIỐNG', maBN: '2604052546', phai: 'Nam' },
  { id: 10, doiTuong: 'Thuốc B.Lẻ', hoTen: 'KL THƯ', maBN: '', phai: 'Nam' },
];

export const chiTietBenhNhan = {
  maBN: '2507043514',
  hoTen: 'DƯƠNG THỊ KIM KHANH',
  gioiTinh: 'Nữ',
  ngaySinh: '15/10/1963',
  tuoi: 63,
  diaChi: 'THÔN 9, Xã Đức Tín, Huyện Đức Linh, Tỉnh Bình Thuận, Xã Hoài Đức, Tỉnh Lâm Đồng',
  bhytPct: 80,
  soThe: 'GD4606021080131',
  tuNgay: '10/07/2025',
  denNgay: '09/07/2026',
  noiDKKCB: '60-015',
  tongChiPhi: '',
  bhytTra: '',
  benhNhanTra: '',
};

export const chiTietToaThuoc = [
  {
    id: 1,
    maThuoc: 'TH001995',
    hoatChat: 'Probiotics, L-lysine Hydrochlori...',
    tenThuoc: 'Biolac Fort (Men)',
    dvt: 'Viên',
    dvKeToa: 'Viên',
    s: 1,
    tr: '',
    ch: '',
    toi: 1,
    sl: 30,
    cachDung: 'Sau ăn',
    donGia: 2000,
    tong: 60000,
    doiTuong: 'THU PHÍ',
    kho: 'Kho Nhà Thuốc Dịch Vụ',
  },
  {
    id: 2,
    maThuoc: 'TH000474',
    hoatChat: 'Dapaglifozin',
    tenThuoc: 'Forxiga',
    dvt: 'Viên',
    dvKeToa: 'Viên',
    s: 1,
    tr: '',
    ch: '',
    toi: '',
    sl: 30,
    cachDung: 'Sau ăn',
    donGia: 25000,
    tong: 750000,
    doiTuong: 'THU PHÍ',
    kho: 'Kho Nhà Thuốc Dịch Vụ',
  },
];

export const danhSachToaThuocDaDuyet = [
  { id: 1, doiTuong: 'BHYT', maBN: '2210007250', hoTen: 'PHẠM THỊ SỐ', namSinh: 1968, gioiTinh: 'Nữ', diaChi: 'Thôn Đức Hạnh 4, Xã Hoài Đức, Huyện Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 2, doiTuong: 'BHYT', maBN: '2401027534', hoTen: 'TRẦN MINH KHANG', namSinh: 2022, gioiTinh: 'Nam', diaChi: 'Thị trấn Đức Tài, Huyện Đức Linh, Tỉnh Bình Thuận', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NHI' },
  { id: 3, doiTuong: 'BHYT', maBN: '2502038783', hoTen: 'NGUYỄN HOA', namSinh: 1947, gioiTinh: 'Nam', diaChi: 'Thôn Đức Tín 8, Xã Hoài Đức, Huyện Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 4, doiTuong: 'BHYT', maBN: '2602050503', hoTen: 'ĐẶNG THỊ CÚC', namSinh: 1963, gioiTinh: 'Nữ', diaChi: 'Thôn Võ Xu 5, Xã Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 5, doiTuong: 'BHYT', maBN: '2502038475', hoTen: 'LÊ THỊ TỐI', namSinh: 1963, gioiTinh: 'Nữ', diaChi: 'Thôn Đức Hạnh 3, Xã Hoài Đức, Huyện Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 6, doiTuong: 'BHYT', maBN: '2308021910', hoTen: 'NGUYỄN SANG', namSinh: 1972, gioiTinh: 'Nam', diaChi: 'KHU PHỐ 6, Thị trấn Đức Tài, Huyện Đức Linh, Tỉnh Bình Thuận', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 7, doiTuong: 'BHYT', maBN: '2502038614', hoTen: 'NGUYỄN THỊ HÀ', namSinh: 1966, gioiTinh: 'Nữ', diaChi: 'Thôn Phú Bình, Xã Tịnh Châu, Thành phố Quảng Ngãi, Tỉnh Quảng ...', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 8, doiTuong: 'BHYT', maBN: '2508045091', hoTen: 'NGUYỄN HỮU BÁ', namSinh: 1968, gioiTinh: 'Nam', diaChi: 'Tổ 5, KP3, Xã Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NGOẠI KHOA' },
  { id: 9, doiTuong: 'BHYT', maBN: '2604052328', hoTen: 'NGUYỄN THANH LONG', namSinh: 1957, gioiTinh: 'Nam', diaChi: 'Thôn 1, Xã Tánh Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 10, doiTuong: 'BHYT', maBN: '2604052546', hoTen: 'VÕ VĂN GIỐNG', namSinh: 1958, gioiTinh: 'Nam', diaChi: 'THÔN 9, Xã Đức Tín, Huyện Đức Linh, Tỉnh Bình Thuận', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 11, doiTuong: 'BHYT', maBN: '2506043101', hoTen: 'NGUYỄN VĂN HÙNG', namSinh: 1968, gioiTinh: 'Nam', diaChi: 'Thôn Nam Hà, Xã Trà Tân, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 12, doiTuong: 'BHYT', maBN: '2512048783', hoTen: 'HUỲNH TRỌNG NGHĨA', namSinh: 1957, gioiTinh: 'Nam', diaChi: 'Xã Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 13, doiTuong: 'BHYT', maBN: '2507043866', hoTen: 'NGUYỄN NAM', namSinh: 1962, gioiTinh: 'Nam', diaChi: 'Thôn Đức Tài 2, Xã Hoài Đức, Huyện Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 14, doiTuong: 'BHYT', maBN: '2507043514', hoTen: 'DƯƠNG THỊ KIM KHANH', namSinh: 1963, gioiTinh: 'Nữ', diaChi: 'THÔN 9, Xã Đức Tín, Huyện Đức Linh, Tỉnh Bình Thuận', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 15, doiTuong: 'BHYT', maBN: '2601049583', hoTen: 'PHẠM THỊ BẦN', namSinh: 1966, gioiTinh: 'Nữ', diaChi: 'Thôn Nam Hà, Xã Trà Tân, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 16, doiTuong: 'BHYT', maBN: '2605053520', hoTen: 'NGUYỄN TẤN ANH', namSinh: 1973, gioiTinh: 'Nam', diaChi: 'Thôn Nam Chính 10, Xã Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 17, doiTuong: 'BHYT', maBN: '2507043905', hoTen: 'HUỲNH THANH TUẤN', namSinh: 1958, gioiTinh: 'Nam', diaChi: 'Thôn Võ Xu 9, Xã Đức Linh, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
  { id: 18, doiTuong: 'BHYT', maBN: '2604053176', hoTen: 'CẤP THỊ ÁNH NHUNG', namSinh: 1989, gioiTinh: 'Nữ', diaChi: 'Thôn 1, Xã Bắc Ruộng, Tỉnh Lâm Đồng', userDuyet: 'Nguyễn Ngọc Anh Thư', phongKham: 'PHÒNG KHÁM NỘI' },
];
